### ISSUE TITLE
Investigate YAML load warning

### ISSUE THREAD

**Issue by kylenstone** [Frameio/fioctl#9]
while running `fioctl accounts get <account_id>`:

```
/Users/kyle/.local/share/virtualenvs/fioctl-RLIdxeQm/lib/python3.7/site-packages/fioctl/config.py:10: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(open(self.filename))
```

**Comment by abhushansahu** [comment]
After checking the flow, I couldn't find any such reported issue in my dev setup. 
This is the result set 
fioctl accounts get *hiddenid*
+--------------------+--------------------------------------+
| attribute          | value                                |
|--------------------+--------------------------------------|
| id                 | *hiddenid* |
| owner.email        | *hiddenid*                    |
| plan.name          | v4-team-mo                           |
| storage            | 0                                    |
| member_count       | 1                                    |
| collaborator_count | 1                                    |
| inserted_at        | 2020-06-06T11:33:43.435204Z          |
+--------------------+--------------------------------------+

**Comment by kylenstone** [comment]
Ah, I see, the current version is `1.1.1` but we haven't updated pypi yet. So the 'public' version is still `1.1` which doesn't have this refactor yet. We'll update pypi soon so I'll close this out.
